language: node_js
node_js: 18
cache: false
dist: focal

jobs:
  include:
  - stage: Publish to npm
    if: branch =~ /(release)/
    script:
    - echo "PUBLISH npm"
    deploy:
      skip_cleanup: true
      provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^(release)*

  - stage: Publish to docker registry
    if: branch =~ /(release)/
    script:
    - echo "PUBLISH docker"
    - export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -Fn '{ print $2 }' | sed 's/[n:",]//g' | tr -d '[[:space:]]')
    - export MAJOR_VERSION=$(echo ${PACKAGE_VERSION} | awk -F. '{ print $1 }')
    - echo Package version ${PACKAGE_VERSION}
    - echo Major version ${MAJOR_VERSION}

    - git config --local user.name ${GIT_USER}
    - git config --local user.email ${GIT_EMAIL}
    - git tag ${PACKAGE_VERSION}

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - docker build -t soajsorg/consoleui .
    - docker tag soajsorg/consoleui:latest soajsorg/consoleui:${PACKAGE_VERSION}
    - docker tag soajsorg/consoleui:latest soajsorg/consoleui:${MAJOR_VERSION}.x

    - docker build -t soajsorg/consoleui-nossl -f Dockerfile_nossl .
    - docker tag soajsorg/consoleui-nossl:latest soajsorg/consoleui-nossl:${PACKAGE_VERSION}
    - docker tag soajsorg/consoleui-nossl:latest soajsorg/consoleui-nossl:${MAJOR_VERSION}.x

    - docker images

    - docker push soajsorg/consoleui
    - docker push soajsorg/consoleui:${PACKAGE_VERSION}
    - docker push soajsorg/consoleui:${MAJOR_VERSION}.x

    - docker push soajsorg/consoleui-nossl
    - docker push soajsorg/consoleui-nossl:${PACKAGE_VERSION}
    - docker push soajsorg/consoleui-nossl:${MAJOR_VERSION}.x

    deploy:
      on:
        all_branches: true
      provider: releases
      api_key: ${GIT_TOKEN}
      skip_cleanup: true
